export enum App {
  YORUBA_CALENDAR = "YORUBA_CALENDAR",
  TAX_FLOW = "TAX_FLOW",
  CLEANING_SERVICE = "CLEANING_SERVICE",
  TICKETING = "TICKETING",
}

export enum UserType {
  INDIVIDUAL = "INDIVIDUAL",
  COMPANY = "COMPANY",
  SME = "SME",
}
