export enum App {
  YORUBA_CALENDAR = "YORUBA_CALENDAR",
  TAX_FLOW = "TAX_FLOW",
  CLEANING_SERVICE = "CLEANING_SERVICE",
  TICKETING = "TICKETING",
}

export enum UserType {
  INDIVIDUAL = "INDIVIDUAL",
  COMPANY = "COMPANY",
  SME = "SME",
}

export enum RoleName {
  USER = "USER",
  CREATOR = "CREATOR",
  MODERATOR = "MODERATOR",
  ADMIN = "ADMIN",
  SUPERADMIN = "SUPERADMIN",
  TAX_MANAGER = "TAX_MANAGER",
  CALENDAR_MANAGER = "CALENDAR_MANAGER",
  TICKET_MANAGER = "TICKET_MANAGER",
  CLEANING_MANAGER = "CLEANING_MANAGER",
}
